name: login_page
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Defines the version and build number for your application.
# Learn more about versioning for Android, iOS, and Windows in their respective links.
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add dependencies
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  fluttertoast: ^8.2.12
  drop_down_list: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  # Ensure the Material Icons font is included in your application.
  uses-material-design: true

  # Define assets
  assets:
    - assets/image1.png
    - assets/image2.png

  # Define custom fonts
  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora-VariableFont_wght.ttf
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf
