// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl-rng2hTFClSAiSQDTgiti0NeE1xYtL4',
    appId: '1:406797164743:web:dcaf97f63afccdb28c9ee2',
    messagingSenderId: '406797164743',
    projectId: 'login-67fee',
    authDomain: 'login-67fee.firebaseapp.com',
    storageBucket: 'login-67fee.firebasestorage.app',
    measurementId: 'G-WEJJ2TPR36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSrwm8ft22UoMuMjT35VjW5t6-rzXFuf8',
    appId: '1:406797164743:android:53044605afb0b81f8c9ee2',
    messagingSenderId: '406797164743',
    projectId: 'login-67fee',
    storageBucket: 'login-67fee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9F-C1tJJI-Xz_1bhLKl2RJKKyfE8izGM',
    appId: '1:406797164743:ios:57a11b5b3a53833f8c9ee2',
    messagingSenderId: '406797164743',
    projectId: 'login-67fee',
    storageBucket: 'login-67fee.firebasestorage.app',
    iosBundleId: 'com.tourapp.tourApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9F-C1tJJI-Xz_1bhLKl2RJKKyfE8izGM',
    appId: '1:406797164743:ios:da97a2f468d73ae28c9ee2',
    messagingSenderId: '406797164743',
    projectId: 'login-67fee',
    storageBucket: 'login-67fee.firebasestorage.app',
    iosBundleId: 'com.company.travelglobeguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl-rng2hTFClSAiSQDTgiti0NeE1xYtL4',
    appId: '1:406797164743:web:37e09f0db9fc9af98c9ee2',
    messagingSenderId: '406797164743',
    projectId: 'login-67fee',
    authDomain: 'login-67fee.firebaseapp.com',
    storageBucket: 'login-67fee.firebasestorage.app',
    measurementId: 'G-THDV7L09KP',
  );
}
